name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.1.1
        with:
          title-regex: "foo"
          on-failed-regex-comment:
            "Your PR title must contain the word foo"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
